apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
    name: veilarbportefoljeflatefs
    namespace: pto
    cluster: dev-fss
    labels:
        team: pto
spec:
    image: ghcr.io/navikt/veilarbportefoljeflatefs/veilarbportefoljeflatefs:{{version}}
    port: 8080
    webproxy: true
    liveness:
        path: veilarbportefoljeflatefs/internal/isAlive
        initialDelay: 5
    readiness:
        path: veilarbportefoljeflatefs/internal/isReady
        initialDelay: 5
    replicas:
        min: 1
        max: 2
        cpuThresholdPercentage: 75
    resources:
        limits:
            cpu: '1'
            memory: 1024Mi
        requests:
            cpu: 500m
            memory: 512Mi
    prometheus:
        enabled: true
        path: veilarbportefoljeflatefs/internal/prometheus
    ingresses:
        - https://veilarbportefoljeflatefs-q1.nais.preprod.local
        - https://app-q1.adeo.no/veilarbportefoljeflatefs
        - https://app-q1.dev.adeo.no/veilarbportefoljeflatefs
    vault:
        enabled: true
    envFrom:
        - configmap: pto-config
