apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbportefoljeflatefs
  namespace: {{namespace}}
  cluster: dev-fss
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbportefoljeflatefs/veilarbportefoljeflatefs:{{version}}
  port: 8080
  webproxy: true
  liveness:
    path: veilarbportefoljeflatefs/internal/isAlive
    initialDelay: 5
  readiness:
    path: veilarbportefoljeflatefs/internal/isReady
    initialDelay: 5
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  prometheus:
    enabled: true
    path: veilarbportefoljeflatefs/internal/prometheus
  ingresses:
    - https://veilarbportefoljeflatefs-{{namespace}}.nais.preprod.local
    - https://app-{{namespace}}.adeo.no/veilarbportefoljeflatefs
  vault:
    enabled: true
  envFrom:
    - configmap: pto-config
