name: Deploy til Q1
on:
    workflow_dispatch:
env:
    IMAGE_TAG: ${{ github.sha }}
    IMAGE: docker.pkg.github.com/${{ github.repository }}/veilarbportefoljeflatefs
    PRINT_PAYLOAD: true

jobs:
    build-project-and-docker-image:
        runs-on: ubuntu-latest
        name: Build project and publish Docker image
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '16'
                  cache: 'npm'
            - run: npm ci
            - name: Build production artifact
              run: npm run build
            - name: Run tests
              run: npm run test
            - name: Build and publish Docker image
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} --password-stdin
                  docker build -t ${IMAGE}:${IMAGE_TAG} .
                  docker push ${IMAGE}:${IMAGE_TAG}
    deploy-dev:
        name: Deploy q1 fss
        needs:
            - build-docker-image
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: dev-fss
                  RESOURCE: nais-dev.yaml
                  VAR: version=${{ env.IMAGE_TAG }},namespace=pto
