name: Cypress testing

on: pull_request
jobs:
    cypress-run:
        name: Cypress run
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install dependencies
              run: npm ci
              env:
                READER_TOKEN: ${{ secrets.READER_TOKEN }}
            - name: Cypress run
              uses: cypress-io/github-action@v5
              with:
                  browser: chrome
                  start: npm start cypress:run
                  wait-on: http://localhost:3000
                  wait-on-timeout: 90
                  record: false
