name: Deploy github pages
on:
    workflow_dispatch:
env:
    IMAGE_TAG: ${{ github.sha }}
    IMAGE: docker.pkg.github.com/${{ github.repository }}/veilarbportefoljeflatefs
    PRINT_PAYLOAD: true

jobs:
    update-gh-pages:
        name: Update GitHub pages
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: '16'
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Build mock application
              run: npm run build:mock
            - name: Update GitHub pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./build